### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by binary-data** [bobbyrenwick/ansible-pip#11]
Just wondering, is this repo maintained? I use this role and it works fine. But I see pull requests that definitely worth to be merged (not critical, but...) and issue that can be closed already.

**Comment by bobbyrenwick** [comment]
Yes, just not very well! I don't have much time for maintenance and tend to forget that I need to do it. I've closed the issue you speak of, and will close this once I've had a look at those PRs
