### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by aral** [bobbyrenwick/ansible-pip#2]
Currently, it installs pip for Python 2.x — would be great to have the option of installing it for 3. I just hacked the source to change the binary but a variable would be good to add.

**Comment by binary-data** [comment]
I definitely used this role to install pip for Python 3 (`- { role: bobbyrenwick.pip, python: python3, pip: pip3 }`), so I think this issue could be closed

**Comment by bobbyrenwick** [comment]
Thanks @binary-data, I'll close the issue based on your usage.
