### ISSUE TITLE
Is this role maintained?

### ISSUE THREAD

**Issue by nmusatti** [bobbyrenwick/ansible-pip#32]
Is this role still maintained? Is any of the maintainer willing to review and apply pull request #31, or if anyone is willing to step up, can they be added as maintainers, both on GitHub and on Galaxy?

**Comment by bobbyrenwick** [comment]
I don't really need this role anymore but I'm happy to add anyone as a maintainer on github, and galaxy if that's what's needed?

I've just merged that PR. Do I need to do anything in Galaxy? It's been a long time since I've done anything to do with ansible!

**Comment by Zialus** [comment]
You'll need something like this [GHA](https://github.com/marketplace/actions/publish-ansible-role-to-galaxy) to push to galaxy.

**Comment by nmusatti** [comment]
> I don't really need this role anymore but I'm happy to add anyone as a maintainer on github, and galaxy if that's what's needed?
> 
> I've just merged that PR. Do I need to do anything in Galaxy? It's been a long time since I've done anything to do with ansible!

Thank you @bobbyrenwick. I'd like to volunteer. If you don't have any objection I'd keep the role under your name in Galaxy, as there is where users are used to finding it. In that case, once you added me as a maintainer here on GitHub, you should be able to add me as a contributor.

**Comment by nmusatti** [comment]
> You'll need something like this [GHA](https://github.com/marketplace/actions/publish-ansible-role-to-galaxy) to push to galaxy.

Before looking into Actions someone needs to be authorized to publish new releases on Galaxy.

**Comment by bobbyrenwick** [comment]
@nmusatti, I've invited you to be a collaborator on github. What is your galaxy username? I've tried searching for the same username and just "nicola" too and I haven't found you.

**Comment by nmusatti** [comment]
It's the same, "nmusatti": https://galaxy.ansible.com/nmusatti Maybe Galaxy doesn't synchronize immediately.

**Comment by bobbyrenwick** [comment]
@nmusatti I've just added you to galaxy now. Hopefully that closes this issue and everything works ok.

I'll close this issue but let me know if there's anything else you need me for. Thanks for taking over!
