### ISSUE TITLE
ImportError: cannot import name IncompleteRead

### ISSUE THREAD

**Issue by jbmusso** [bobbyrenwick/ansible-pip#6]
Greetings. In an attempt to ensure pip is installed (see https://github.com/angstwad/docker.ubuntu/issues/28), I did a quick playbook:
```yaml
---
- hosts: staging
  roles:
    - bobbyrenwick.pip
    - angstwad.docker_ubuntu
```

Several tasks are being skipped (unsure why):

``
`
TASK: [bobbyrenwick.pip | check to see if pip is already installed] ***********
changed: [staging.foobar.com]

TASK: [bobbyrenwick.pip | download pip] ***************************************
skipping: [staging.foobar.com]

TASK: [bobbyrenwick.pip | install pip] ****************************************
skipping: [staging.foobar.com]

TASK: [bobbyrenwick.pip | delete get-pip.py] **********************************
skipping: [staging.foobar.com]

TASK: [bobbyrenwick.pip | check to see if pip is installed at the correct version] ***
skipping: [staging.foobar.com]

TASK: [bobbyrenwick.pip | install required version of pip] ********************
skipping: [staging.foobar.com]
```

I'm then getting the following error:
```
TASK: [angstwad.docker_ubuntu | Install Docker-py] ****************************
failed: [staging.foobar.com] => {"cmd": "/usr/bin/pip install docker-py", "failed": true}
msg:
:stderr: Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

I ssh'ed into the remote instance (Ubuntu 14.04.1) and did a quick n dirty `easy_install pip`. I'm no longer getting the error message when replaying the playbook.

I hope I'm not missing the obvious - I just started with Ansible and still learning. I can provide more information if needed. Thanks!

**Comment by bobbyrenwick** [comment]
It looks as though you don't need this role because the `angstwad.docker_ubuntu` role already [installs pip](https://github.com/angstwad/docker.ubuntu/blob/master/tasks/main.yml#L101-L109)
